server:
  port: 8080

spring:
  profiles:
    active:
  datasource:
    url: jdbc:mysql://localhost/expensedb
    username: root
    password: Pas$4MyLocalSQL
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true